#!/bin/bash

set -euxo pipefail

nfs_setup {
   sudo mkdir -p /mnt/skynet
   set +e
   sudo umount /mnt/skynet
   set -e
   sudo chown -R pi:pi /mnt/skynet
   cp /etc/fstab /var/tmp
sudo cat <<_EOF_ >>/var/tmp/fstab
192.168.2.220:/volume1/Skynet	/mnt/skynet	nfs	rw,hard,intr,nolock,rsize=32768,wsize=32768	0 0
_EOF_
   sudo cp /var/tmp/fstab /etc/fstab
   cat /etc/fstab
}

if [ ! -f .gecko_runonce ]; then
   touch .gecko_runonce
#   nfs_setup
   sudo apt-get update
   sudo systemctl enable ssh
   sudo systemctl start ssh
   sudo apt-get install emacs nfs-common -y
   #   sudo apt-get install python-pygame -y
   sudo apt-get install python-pip -y
   sudo pip install evdev
   sudo apt-get remove --purge libreoffice-* -y
   sudo apt-get remove --purge wolfram-engine -y
   sudo apt-get upgrade -y
   sudo apt-get clean
   sudo reboot
fi

ifconfig
sudo mount -a
URL_SRC="https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/pi-eyes.sh"
curl ${URL_SRC} > pi-eyes.sh

sudo bash pi-eyes.sh
