#!/bin/bash

set -euxo pipefail

sudo modprobe loop
set +e
sudo losetup -a

LOOPDEV=$(sudo losetup -f)
echo "LOOPDEV: ${LOOPDEV}"

# Validate argument count here

F_IMAGE=$1

sudo chown peck:peck ${F_IMAGE}

## COMMAND RUN AND OUTPUT EXCERPTED BELOW
#sudo fdisk -l ${F_IMAGE}

#Disk 2019-03-25b_preload.img: 59.5 GiB, 63864569856 bytes, 124735488 sectors
#Units: sectors of 1 * 512 = 512 bytes
#Sector size (logical/physical): 512 bytes / 512 bytes
#I/O size (minimum/optimal): 512 bytes / 512 bytes
#Disklabel type: dos
#Disk identifier: 0x71cce890

#Device                   Boot Start       End   Sectors  Size Id Type
#2019-03-25b_preload.img1       8192     98045     89854 43.9M  c W95 FAT32 (LBA)
#2019-03-25b_preload.img2      98304 124735487 124637184 59.4G 83 Linux

START=98304

set +e
sudo losetup -d ${LOOPDEV}
set -e

# COMMAND RUN AND OUTPUT EXCERPTED BELOW
sudo losetup ${LOOPDEV} ${F_IMAGE} -o $((START*512))
#sudo gparted ${LOOPDEV}

# Free space preceding (MiB):  0
# New size (MiB):  2646
# Free space following (MiB):  58232
# Align to:  MiB

# resize2fs -p ${LOOPDEV} 1410048K

NEWSIZE=2646

set +e
sudo losetup -d ${LOOPDEV}
set -e

#exit 0

sudo losetup ${LOOPDEV} ${F_IMAGE}
set +e
sudo fdisk ${LOOPDEV} <<EOF
d
2
n
p
2
${START}
+${NEWSIZE}M
w
EOF
set -e

# Confirm changes
sudo fdisk -l ${LOOPDEV}

#Disk /dev/loop0: 59.5 GiB, 63864569856 bytes, 124735488 sectors
#Units: sectors of 1 * 512 = 512 bytes
#Sector size (logical/physical): 512 bytes / 512 bytes
#I/O size (minimum/optimal): 512 bytes / 512 bytes
#Disklabel type: dos
#Disk identifier: 0x71cce890

#Device       Boot Start     End Sectors  Size Id Type
#/dev/loop0p1       8192   98045   89854 43.9M  c W95 FAT32 (LBA)
#/dev/loop0p2      98304 5517311 5419008  2.6G 83 Linux

END=5517311

set +e
sudo losetup -d ${LOOPDEV}
set -e

F_IMAGE_NEW=${F_IMAGE}.trunc
mv ${F_IMAGE} ${F_IMAGE_NEW}
truncate -s $(((END+1)*512)) ${F_IMAGE_NEW}

exit 0

# ERROR:  Mount below doesn't succeed
sudo losetup ${LOOPDEV} ${F_IMAGE_NEW} -o $((START*512))
sudo mkdir -p /mnt/imageroot
sudo mount ${LOOPDEV} /mnt/imageroot
sudo dcfldd if=${LOOPDEV} of=/mnt/imageroot/zero.txt
sudo rm /mnt/imageroot/zero.txt
sudo umount /mnt/imageroot
sudo rmdir /mnt/imageroot
set +e
sudo losetup -d ${LOOPDEV}
set -e

exit 0

gzip ${F_IMAGE_NEW}

# Actions on client side
#sudo raspi-config --expand-rootfs
#sudo shutdown -r now
